name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    #Not currently publishing to Azure, commenting out
    #- uses: azure/appservice-actions/webapp@master
    #  with:
    #    app-name: dotnetcorewebapp19
    #    publish-profile: ${{ secrets.publish_profile }}
    #    package: "bin/Release/netcoreapp3.0"



    # This works, commented out so it doesn't break the build.
    #- name: Run Snyk to check for vulnerabilities
    #  uses: snyk/actions/dotnet@master
    #  env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # This does not work, yet.
    #https://github.com/sonatype-nexus-community/nancy-github-action 
    #- name: Nancy
    #  uses: sonatype-nexus-community/nancy-github-action@master
    #  with:
    #    target: go.sum


  #This works, but it's a person's personal repo, which means RISK.    
  # ref: https://github.com/svdarren/secrets-workflow/blob/9633bc1195a1ca1d4d70415aa4eff6cf55d706de/.github/workflows/secrets.yml
  #gitleak:
  #  name: gitleaks
  #  runs-on: ubuntu-latest

  #  steps:
  #    - uses: actions/checkout@v2

  #    - name: Install dependencies
  #      run: docker pull zricethezav/gitleaks
  #    - uses: fmigneault/gitleaks-action@master
  #    - uses: CySeq/gitcret@v2
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


   # This runs, but does not find any secrets.
   #Adding Secret-scan from Github staff
    -  name: Secret Scan
       uses: max/secret-scan@1.0.0
    - uses: actions/upload-artifact@v1
      with:
        name: secretscanreport
        path: reports  
   
   #Does not work, yet.
   #https://github.com/marketplace/actions/federacy-salus-security-scan
    #- name: Federacy Salus Security Scan Example
    #- uses: actions/checkout@v1
    #- name: Federacy Salus Scan
    #  id: salus_scan
    #  uses: federacy/scan-action@v1  
    #- uses: actions/upload-artifact@v1
    #  with:
    #    report_uri: "https://www.securedevelopment.com/collector/salus_scans/71757b98-4b14-4ca7-89d7-3150074612bf"  
        

    # This runs successfully but does not provide useful results
    #Scan OSS - open source security issues
    #- name: sast-scan
    #  uses: AppThreat/sast-scan-action@1.0.2
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: SASTreports
    #    path: reports
    
    # This runs successfully but can't seem to find the dependencies file
    #Security audit of dependencies 
    #- uses: AppThreat/dep-scan-action@master
    #  env:
    #    VULNDB_HOME: ${{ github.workspace }}/db
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: DEPreports
    #    path: reports
    
    #This works. However. my azure instance is down right now, so let's skip it.
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #- name: dotnet publish
    #  run: |
    #    dotnet publish -c Release -o dotnetcorewebapp 
    #- name: 'Run Azure webapp deploy action using publish profile credentials'
    #  uses: azure/webapps-deploy@v1
    #  with: 
    #    app-name: dotnetcorewebapp19 # Replace with your app name
    #    publish-profile: ${{ secrets.publish_profile }} # Define secret variable in repository settings as per action documentation
    #    package: './dotnetcorewebapp' 
